Creating Numpy Arrays

In [4]:
import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [10]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
#np.ones and zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#np.random
np.random.random((3,4))

array([[0.21899362, 0.42779303, 0.79372911, 0.08740246],
       [0.58350929, 0.06439929, 0.31387545, 0.58833033],
       [0.91346695, 0.49278931, 0.10375812, 0.86191929]])

In [20]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [22]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
#ndim
a3.ndim


3

In [27]:
#shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
#size
a3.size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [31]:
#itemsize
a3.itemsize

4

In [32]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


Changing Datatype

In [35]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Array Operations

In [36]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
#scalar operations
#arithmetic

a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [38]:
#relational
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [40]:
#vector operations
#arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Functions

In [41]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[36., 95., 19.],
       [11., 37., 65.],
       [70., 98., 86.]])

In [46]:
#max/min/sum/prod
#0 -> col and 1 -> row
np.prod(a1,axis=1)

array([ 64980.,  26455., 589960.])

In [47]:
#mean/median/std/var
np.mean(a1,axis=1)

array([50.        , 37.66666667, 84.66666667])

In [48]:
#trigonomoetric functions
np.sin(a1)

array([[-0.99177885,  0.68326171,  0.14987721],
       [-0.99999021, -0.64353813,  0.82682868],
       [ 0.77389068, -0.57338187, -0.92345845]])

In [51]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [53]:
#log and exponents
np.log(a1)
np.exp(a1)

array([[4.31123155e+15, 1.81123908e+41, 1.78482301e+08],
       [5.98741417e+04, 1.17191424e+16, 1.69488924e+28],
       [2.51543867e+30, 3.63797095e+42, 2.23524660e+37]])

In [58]:
#round/floor/ceil
# np.round(np.random.random((2,3))*100)
# np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[36., 11., 81.],
       [25., 90., 28.]])

Indexing and Slicing

In [59]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a1[-0]

0

In [64]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a2[1,2]

6

In [66]:
a2[2,3]

11

In [67]:
a2[1,0]

4

In [68]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [69]:
a3[1,0,1]

5

In [70]:
a3[0,1,0]

2

In [71]:
a3[0,0,0]

0

In [72]:
a3[1,1,0]

6

Slicing

In [73]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a1[2:5]

array([2, 3, 4])

In [75]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
a2[0,:]

array([0, 1, 2, 3])

In [77]:
a2[:,2]

array([ 2,  6, 10])

In [80]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [81]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [83]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [86]:
a2[1,::3]

array([4, 7])

In [94]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [95]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [98]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [100]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [109]:
a3[0::3,1::2]

array([[[3, 4, 5]]])

In [110]:
a3[1,:1]

array([[ 9, 10, 11]])

In [111]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [112]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [118]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [123]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [120]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [121]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [125]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [127]:
for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [ ]:
#reshape


In [128]:
#Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [130]:
#revel
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

In [132]:
#horzontal staacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [134]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [135]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Splitting

In [136]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [138]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]