PYTHON NUMPY ARRAYS

In [5]:
# import the library
import numpy as np

In [10]:
lst=[1,2,3,4]
arr=np.array(lst)

In [11]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(4,)

In [16]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]
# np.array([lst1,lst2,lst3])
arr1=np.array([lst1,lst2,lst3])


In [17]:
arr1.shape

(3, 5)

In [18]:
arr

array([1, 2, 3, 4])

In [19]:
#indexing
arr[3]

4

In [21]:
arr[1:3]

array([2, 3])

In [22]:
arr[1:]

array([2, 3, 4])

In [23]:
arr[:-1]

array([1, 2, 3])

In [24]:
arr[::]

array([1, 2, 3, 4])

In [25]:
arr[::-1]

array([4, 3, 2, 1])

In [26]:
arr[::-2]

array([4, 2])

In [29]:
arr[1::3]

array([2])

In [30]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [40]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [41]:
arr1[:,3:].shape

(3, 2)

In [55]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [56]:
arr1[:,1]

array([2, 3, 4])

In [57]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [37]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [58]:
##EDA
arr

array([1, 2, 3, 4])

In [60]:
arr[arr<2]

array([1])

In [61]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [64]:
#mechanism to create an array
np.arange(1,20,2) .reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [65]:
#mechanism to create an array
np.arange(1,20,2) .reshape(1,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [66]:
#mechanism to create an array
np.arange(1,20,2) .reshape(1,10,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [67]:
arr

array([1, 2, 3, 4])

In [68]:
arr*arr

array([ 1,  4,  9, 16])

In [69]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [70]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [71]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.random.randint(10,50)

11

In [78]:
np.random.randint(10,50,4)

array([48, 35, 38, 12])

In [80]:
np.random.randint(10,50,4).reshape(2,2)

array([[14, 45],
       [13, 38]])

In [81]:
np.random.randn(5,6)

array([[-1.19803446,  0.03798551, -1.86728971,  1.18325709, -0.83741588,
         1.01953625],
       [ 1.22734306, -0.33520646, -0.75517631, -1.03067853,  0.2849677 ,
        -0.86673987],
       [ 1.06555996, -0.76287164,  1.047197  , -0.3205398 , -0.91974281,
         1.34072414],
       [ 0.5550721 ,  1.18660443, -0.22234667,  1.11148776,  0.66910089,
        -0.25192916],
       [-0.36439461, -1.34697966, -0.11607326, -1.445093  , -1.10490879,
        -0.550318  ]])