np.sort

Return a sorted copy of an array

In [2]:
#code
import numpy as np
a = np.random.randint(1,100,15)

a

array([30, 80,  6, 43,  9, 52, 35, 44, 77, 88, 32, 17,  2, 82, 40])

In [3]:
b = np. random.randint(1,100,24).reshape(6,4)
b

array([[23, 92, 71, 92],
       [61, 99, 95, 57],
       [41, 58, 65, 28],
       [99, 86, 44, 48],
       [22, 93, 39, 27],
       [83, 53, 12, 70]])

In [3]:
# ascending
np.sort(a)

array([ 6, 16, 27, 35, 36, 40, 45, 48, 49, 63, 71, 76, 76, 95, 96])

In [6]:
# deciding
np.sort(a)[::-1]

array([96, 95, 76, 76, 71, 63, 49, 48, 45, 40, 36, 35, 27, 16,  6])

In [4]:
np.sort(b,axis=0)

array([[36,  5, 17, 15],
       [56, 10, 41, 16],
       [80, 27, 49, 27],
       [83, 66, 59, 36],
       [84, 82, 75, 46],
       [91, 97, 80, 56]])

In [5]:
np.sort(b,axis=1)

array([[10, 46, 80, 84],
       [27, 41, 56, 66],
       [36, 59, 80, 82],
       [ 5, 15, 36, 75],
       [16, 27, 49, 91],
       [17, 56, 83, 97]])

np.append

In [7]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [8]:
np.append(a,200)

array([ 27,  36,  63,  40,  49,  76,  45,  48,  76,   6,  35,  96,  95,
        16,  71, 200])

In [9]:
b

array([[84, 10, 80, 46],
       [56, 66, 41, 27],
       [80, 82, 59, 36],
       [36,  5, 75, 15],
       [91, 27, 49, 16],
       [83, 97, 17, 56]])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[84., 10., 80., 46.,  1.],
       [56., 66., 41., 27.,  1.],
       [80., 82., 59., 36.,  1.],
       [36.,  5., 75., 15.,  1.],
       [91., 27., 49., 16.,  1.],
       [83., 97., 17., 56.,  1.]])

np.concatenate

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

In [17]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [18]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

np.expand_dims

In [19]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [21]:
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=0)

array([[27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71]])

In [22]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [23]:
np.expand_dims(a,axis=1)

array([[27],
       [36],
       [63],
       [40],
       [49],
       [76],
       [45],
       [48],
       [76],
       [ 6],
       [35],
       [96],
       [95],
       [16],
       [71]])

np.where

In [24]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [25]:
# find all indices with value greater then 50
np.where(a>50)

(array([ 2,  5,  8, 11, 12, 14], dtype=int64),)

In [26]:
#replace all values > 50 with 0
# np.where(condition,true,false)
np.where(a>50,0,a)

array([27, 36,  0, 40, 49,  0, 45, 48,  0,  6, 35,  0,  0, 16,  0])

In [27]:
np.where(a%2 == 0,0,a)

array([27,  0, 63,  0, 49,  0, 45,  0,  0,  0, 35,  0, 95,  0, 71])

np.argmax

In [28]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [29]:
np.argmax(a)

11

In [30]:
b

array([[84, 10, 80, 46],
       [56, 66, 41, 27],
       [80, 82, 59, 36],
       [36,  5, 75, 15],
       [91, 27, 49, 16],
       [83, 97, 17, 56]])

In [33]:
np.argmax(b,axis=1)

array([0, 1, 1, 2, 0, 1], dtype=int64)

In [34]:
np.argmax(b,axis=0)

array([4, 5, 0, 5], dtype=int64)

np.argmin

In [35]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [36]:
np.argmin(a)

9

np.cumsum

In [37]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [38]:
np.cumsum(a)

array([ 27,  63, 126, 166, 215, 291, 336, 384, 460, 466, 501, 597, 692,
       708, 779])

In [39]:
b

array([[84, 10, 80, 46],
       [56, 66, 41, 27],
       [80, 82, 59, 36],
       [36,  5, 75, 15],
       [91, 27, 49, 16],
       [83, 97, 17, 56]])

In [41]:
np.cumsum(b,axis = 0)

array([[ 84,  10,  80,  46],
       [140,  76, 121,  73],
       [220, 158, 180, 109],
       [256, 163, 255, 124],
       [347, 190, 304, 140],
       [430, 287, 321, 196]])

In [42]:
np.cumsum(b,axis = 1)

array([[ 84,  94, 174, 220],
       [ 56, 122, 163, 190],
       [ 80, 162, 221, 257],
       [ 36,  41, 116, 131],
       [ 91, 118, 167, 183],
       [ 83, 180, 197, 253]])

In [40]:
np.cumsum(b)

array([  84,   94,  174,  220,  276,  342,  383,  410,  490,  572,  631,
        667,  703,  708,  783,  798,  889,  916,  965,  981, 1064, 1161,
       1178, 1234])

np.cumprod

In [43]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [44]:
np.cumprod(a)

array([         27,         972,       61236,     2449440,   120022560,
         531779968, -1839705216,  1888462848,  1789255680,  2145599488,
        2081538048, -2035810304,  -128450560, -2055208960,   109051904])

In [45]:
b

array([[84, 10, 80, 46],
       [56, 66, 41, 27],
       [80, 82, 59, 36],
       [36,  5, 75, 15],
       [91, 27, 49, 16],
       [83, 97, 17, 56]])

In [46]:
np.cumprod(b,axis = 1)

array([[      84,      840,    67200,  3091200],
       [      56,     3696,   151536,  4091472],
       [      80,     6560,   387040, 13933440],
       [      36,      180,    13500,   202500],
       [      91,     2457,   120393,  1926288],
       [      83,     8051,   136867,  7664552]])

In [47]:
np.cumprod(b,axis =0)

array([[        84,         10,         80,         46],
       [      4704,        660,       3280,       1242],
       [    376320,      54120,     193520,      44712],
       [  13547520,     270600,   14514000,     670680],
       [1232824320,    7306200,  711186000,   10730880],
       [-754796544,  708701400, -794739888,  600929280]])

np.percentile

In [48]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [49]:
np.percentile(a,100)

96.0

In [50]:
np.percentile(a,0)

6.0

In [51]:
np.percentile(a,50)

48.0

In [52]:
b

array([[84, 10, 80, 46],
       [56, 66, 41, 27],
       [80, 82, 59, 36],
       [36,  5, 75, 15],
       [91, 27, 49, 16],
       [83, 97, 17, 56]])

In [53]:
np.percentile(b,100,axis =0)

array([91., 97., 80., 56.])

In [54]:
np.percentile(b,100,axis =1)

array([84., 66., 82., 75., 91., 97.])

np.histogram

In [55]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [56]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 1, 1, 2, 4, 0, 1, 3, 0, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef

In [57]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

In [58]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [59]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False])

In [60]:
a[np.isin(a,items)]

array([40])

np.flip

In [61]:
a

array([27, 36, 63, 40, 49, 76, 45, 48, 76,  6, 35, 96, 95, 16, 71])

In [62]:
np.flip(a)

array([71, 16, 95, 96, 35,  6, 76, 48, 45, 76, 49, 40, 63, 36, 27])

In [63]:
b

array([[84, 10, 80, 46],
       [56, 66, 41, 27],
       [80, 82, 59, 36],
       [36,  5, 75, 15],
       [91, 27, 49, 16],
       [83, 97, 17, 56]])

In [64]:
np.flip(b)

array([[56, 17, 97, 83],
       [16, 49, 27, 91],
       [15, 75,  5, 36],
       [36, 59, 82, 80],
       [27, 41, 66, 56],
       [46, 80, 10, 84]])

In [65]:
np.flip(b,axis = 0)

array([[83, 97, 17, 56],
       [91, 27, 49, 16],
       [36,  5, 75, 15],
       [80, 82, 59, 36],
       [56, 66, 41, 27],
       [84, 10, 80, 46]])

In [66]:
np.flip(b,axis =1)

array([[46, 80, 10, 84],
       [27, 41, 66, 56],
       [36, 59, 82, 80],
       [15, 75,  5, 36],
       [16, 49, 27, 91],
       [56, 17, 97, 83]])

np.put

In [3]:
a

array([76, 13, 91, 43, 35, 56, 51, 89, 70, 26, 51, 91, 92, 40, 72])

In [4]:
np.put(a,[0,1],[110,530])

In [5]:
a

array([110, 530,  91,  43,  35,  56,  51,  89,  70,  26,  51,  91,  92,
        40,  72])

np.delete

In [8]:
a

array([110, 530,  91,  43,  35,  56,  51,  89,  70,  26,  51,  91,  92,
        40,  72])

In [9]:
np.delete(a,0)

array([530,  91,  43,  35,  56,  51,  89,  70,  26,  51,  91,  92,  40,
        72])

In [10]:
a

array([110, 530,  91,  43,  35,  56,  51,  89,  70,  26,  51,  91,  92,
        40,  72])

set functions

In [13]:
#np.union1d
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# np.intersect1d
np.intersect1d(m,n)

array([3, 4, 5])

In [17]:
# np.setdiff1d
np.setdiff1d(m,n)


array([1, 2])

In [18]:
# np.setxor1d
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [19]:
# np.in1d
np.in1d(m,10)

array([False, False, False, False, False])

np.clip

In [4]:
a

array([30, 80,  6, 43,  9, 52, 35, 44, 77, 88, 32, 17,  2, 82, 40])

In [5]:
np.clip(a,a_min=25,a_max=75)

array([30, 75, 25, 43, 25, 52, 35, 44, 75, 75, 32, 25, 25, 75, 40])