In [1]:
import numpy as np

In [3]:
ar = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(ar))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [4]:
ar = np.array([3,4,1,7,8])
s = np.where(ar == 4)
print (s)

(array([1], dtype=int64),)


In [5]:
ar = np.array([3,4,1,7,8])
s = np.where(ar % 4 == 0)
print (s)

(array([1, 4], dtype=int64),)


In [8]:
ar = np.array([1,2,3,4,5])
ss = np.searchsorted(ar, 5)
print(ss)

4


In [10]:
#finter
ar = np.array([20,30,40,50])
fa = [True, False, True, False]
new = ar[fa]
print(new)

[20 40]


In [11]:
ar =np.array([20,30,40,50])
fa = ar>35

new = ar[fa]
print (new)

[40 50]


In [12]:
ar= np.array([2,3,4,5])
fa = ar%2 == 1

new = ar[fa]
print(new)

[3 5]


Aggregating Functions in Numpy

In [3]:
a = np.array([20,40,60,70])
print(np.min(a))
print(np.sum(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))


20
190
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [10]:
a = [190,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price,"\n" ,quantity)
print()
c = np.cumprod([price,quantity], axis = 0)
print(c)
print(c[1].sum())

[190 150 199 200 250 130] 
 [10 50 30 40 30 10]

[[ 190  150  199  200  250  130]
 [1900 7500 5970 8000 7500 1300]]
32170
