In [1]:
import numpy as np

In [3]:
arr= np.array([10,20,30,40])
type(arr)

numpy.ndarray

In [4]:
arr

array([10, 20, 30, 40])

slicing

In [13]:
arr2= np.array([[10,20,30,40],[50,60,70,80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [14]:
arr3= np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [7]:
print(arr[0:3])

[10 20 30]


In [8]:
arr[3:]

array([40])

In [10]:
arr[2:]

array([30, 40])

In [12]:
arr[:2]

array([10, 20])

In [18]:
arr2[0:2,0:2]

array([[10, 20],
       [50, 60]])

In [21]:
arr2[1,2:4]

array([70, 80])

In [22]:
arr3[2,2]

60

In [26]:
np.shape(arr3)

(3, 4)

In [27]:
np.size(arr3)

12

In [28]:
np.ndim(arr3)

2

In [29]:
arr.dtype

dtype('int32')

Inspecting an Array

In [31]:
a =[30,40,20,40,30]
arr = np.array(a)
print(arr)
print(arr.shape)

[30 40 20 40 30]
(5,)


In [36]:
b = [[30,40],[40,30]]
arr = np.array(b)
print(arr)
print(arr.shape)
print(len(arr))


[[30 40]
 [40 30]]
(2, 2)
2


In [40]:
b = [[30,40,40],[40,30,10]]
arr = np.array(b)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.dtype)
print(arr.astype(float))

[[30 40 40]
 [40 30 10]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int32
[[30. 40. 40.]
 [40. 30. 10.]]


Mathematical Operations and Functions on Arrays

In [44]:
a1 =np.array([30,40,60,20,10])
b2 =np.array([30,20,10,20,20])
print(a1+b2)
print(np.add(a1,b2))

[60 60 70 40 30]
[60 60 70 40 30]


In [46]:
a1 =np.array([[30,40],[60,20]])
b2 =np.array([[30,20],[10,20]])
print(a1+b2)
print(np.add(a1,b2))

[[60 60]
 [70 40]]
[[60 60]
 [70 40]]


In [47]:
a1 =np.array([[30,40],[60,20]])
b2 =np.array([[30,20],[10,20]])
print(a1- b2)
print(np.subtract(a1,b2))

[[ 0 20]
 [50  0]]
[[ 0 20]
 [50  0]]


In [49]:
a1 =np.array([[30,40],[60,20]])
b2 =np.array([[30,20],[10,20]])
print(a1*b2)
print(np.multiply(a1,b2))

[[900 800]
 [600 400]]
[[900 800]
 [600 400]]


In [51]:
a1 =np.array([[30,40],[60,20]])
b2 =np.array([[30,20],[10,20]])
print(a1/b2)
print(np.divide(a1,b2))

[[1. 2.]
 [6. 1.]]
[[1. 2.]
 [6. 1.]]


In [54]:
x1 = np.array([3,4,2,1])
x2 = np.array([3])
print(np.power(x1,x2))

[27 64  8  1]


In [2]:
x1 = np.array([27,64,8,1])
print(np.sqrt(x1))

[5.19615242 8.         2.82842712 1.        ]


Combining and Splitting Arrays

In [3]:
a = [30,40,50]
b =[5,5,3]
print(a + b)

[30, 40, 50, 5, 5, 3]


In [11]:
#Concatenate
arr1 = np.array([30,40,50])
arr2 = np.array([5,5,3])
print(np.concatenate([arr1,arr2]))

[30 40 50  5  5  3]


In [13]:
arr1 = np.array([[30,40],[50,60]])
arr2 = np.array([[5,5],[3,4]])
print(np.concatenate([arr1,arr2],axis = 1))

[[30 40  5  5]
 [50 60  3  4]]


In [15]:
print(np.hstack([arr1,arr2])) #horizontal concatenation

[[30 40  5  5]
 [50 60  3  4]]


In [17]:
print(np.vstack([arr1,arr2])) #vertical concation

[[30 40]
 [50 60]
 [ 5  5]
 [ 3  4]]


In [22]:
a =np.array([[20,40,30],[40,10,20]])
b = print(np.array_split(a,5))
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32), array([], shape=(0, 3), dtype=int32)]
None


Adding and Removing Elements in the Arrays

In [24]:
a =np.array([20,40,60,80])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [26]:
print(np.insert(a,1,50)) #array,index,value

[20 50 40 60 80]


In [27]:
a = np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [28]:
print(np.insert(a,1,[50,60],axis = 0)) 

[[20 40]
 [50 60]
 [60 80]]


In [29]:
print(np.insert(a,[1,2],[50],axis = 0))

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [30]:
print(np.delete(a,1))

[20 60 80]


In [31]:
print(a)
print()
print(np.delete(a,1, axis = 1))

[[20 40]
 [60 80]]

[[20]
 [60]]
