PANDAS

In [3]:
import pandas as pd
import numpy as np

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
## Create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3',
                                                      'Row4','Row5'],columns=['Column1',
                                                                             'Column2',
                                                                             'Column3',
                                                                             'Column4',])


In [6]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
df.tail()


Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [8]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [7]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [8]:
#Indexing
# columnname,rowindex[Loc],rowindex columindex number[.iloc]

df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [11]:
##Columnname
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [14]:

type(df['Column1'])

pandas.core.series.Series

In [13]:
df[['Column1','Column2','Column3']]

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [12]:
type(df[['Column1','Column2','Column3']])

pandas.core.frame.DataFrame

In [17]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [18]:
type(df.loc['Row1'])

pandas.core.series.Series

In [20]:
##using row index name loc
df.loc[['Row1','Row2']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7

In [21]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [35]:
df.iloc[0:,0:4:3]

Column1  Column4
Row1        0        3
Row2        4        7
Row3        8       11
Row4       12       15
Row5       16       19

In [25]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [37]:
##convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [38]:
##Basic operation
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [39]:
## Create Dataframe
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=['Row1','Row2'],columns=['Column1',
                                                                             'Column2',
                                                                             'Column3'
                                                                             ])

In [40]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [41]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [42]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [43]:
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [44]:
df['Column3'].value_counts()

Column3
2    1
4    1
Name: count, dtype: int64

In [45]:
df['Column3'].unique()

array([2, 4], dtype=int64)

In [47]:
df['Column2'].unique()

array([ 1,  5,  9, 13, 17])

In [48]:
df['Column2'].value_counts()

Column2
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [49]:
df>2

Column1  Column2  Column3  Column4
Row1    False    False    False     True
Row2     True     True     True     True
Row3     True     True     True     True
Row4     True     True     True     True
Row5     True     True     True     True

In [50]:
df['Column2']>2

Row1    False
Row2     True
Row3     True
Row4     True
Row5     True
Name: Column2, dtype: bool

In [51]:
df[df['Column2']>2]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19